### PR TITLE
Implementation for Microsoft Office PPT and PPTX to PDF

### PR DESCRIPTION
**Pull request by mistaguy**
This implementation is done and works well. It converts Microsoft PPTX and PPTX to PDF. I think it will be worth adding to document4j

### CODE REVIEW

**Comment by raphw** [comment]
Awesome, thanks for the pull request. I will merge this as soon as possible, I just need to get my hands on a Windows machine.

**Comment by raphw** [comment]
How did you validate the working of the PowerPoint converter? The tests could not possibly work when you committed them, they still referenced the MS Excel formats.

Did you run the tests locally? Could you look into the tests that I now fixed? They do not work for me and I wonder what makes them work on your machine. Thanks for looking into this.

**Comment by mistaguy** [comment]
@raphw i have not taken a keen look at the test since i did this implementation of the excel implementation. I am using this suggested powerpoint implementation in some project. I did regression test without the automated one and all is okay. 

So let us just address the test cases to work properly as you suggested. I am looking into the your tests ;)

**Comment by raphw** [comment]
Hi moved the pull request to the *powerpoint* branch now where I fixed the things I found to be left with the Excel references. For me to merge the branch, running

```bash
mvn clean install -Pms-office
```

needs to work for the PowerPoint project. Can you look into it?

**Comment by mistaguy** [comment]
Alright let me do so

**Comment by raphw** [comment]
I appreciate it. Let me know if something is unclear. The test harness should be straight-forward, I am sure its a small mistake somewhere.

**Comment by mistaguy** [comment]
The test fails:

`Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.328 sec <<< FAILURE! - in com.documents4j.conversion.msoffice.MicrosoftPowerpointStartStopTest
testStartup(com.documents4j.conversion.msoffice.MicrosoftPowerpointStartStopTest)  Time elapsed: 1.034 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected state: MS Office component is not running expected:<3> but was:<-6>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at com.documents4j.conversion.msoffice.MicrosoftOfficeAssertionEngine.assertRunning(MicrosoftOfficeAssertionEngine.java:30)
        at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeStartStopTest.startUpAndShutDown(AbstractMicrosoftOfficeStartStopTest.java:42)
        at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeStartStopTest.testStartup(AbstractMicrosoftOfficeStartStopTest.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.lang.Thread.run(Thread.java:744)


Results :

Failed tests:
  MicrosoftPowerpointConversionTest.setUpConverter:40->AbstractMicrosoftOfficeBasedTest.setUp:41 Unexpected state: MS Office component is not running expected:<3> but was:<-6>
  MicrosoftPowerpointInaccessibilityTest.setUpConverter:20->AbstractMicrosoftOfficeBasedTest.setUp:41 Unexpected state: MS Office component is not running expected:<3> but was:<-6>
  MicrosoftPowerpointStartStopTest>AbstractMicrosoftOfficeStartStopTest.testStartup:30->AbstractMicrosoftOfficeStartStopTest.startUpAndShutDown:42 Unexpected state: MS Office component is not running expected:<3> but was:<-6>

Tests run: 3, Failures: 3, Errors: 0, Skipped: 0`

That is the reason as to why i ended up twisting the script abit for it to work.

**Comment by raphw** [comment]
What you did was to start MS PowerPoint for every single conversion. Excel has a similar twist where it shuts down automatically if no worksheet is opened. I assume that one needs to find a similar twist for PowerPoint.

**Comment by mistaguy** [comment]
I added an option to make sure that the excel application/object is visible. So that tests work just fine. Out of 18 only six are failing. see gits https://gist.github.com/mistaguy/83f07f552fd1e596adc628f0c7181bfc

**Comment by raphw** [comment]
I will have a look at it some time soon. Thank you so far!

**Comment by raphw** [comment]
Sorry but I did not get this to work. There must be a good way to keep PowerPoint running but the scripts as you proposed them are not doing this. I cannot merge this before PowerPoint is reliable.

**Comment by mistaguy** [comment]
i will look at it and see if i can improve it

**Comment by raphw** [comment]
Great, thanks for the effort. Ping me if you have questions.

One requirement would be that there are running tests similar to those for Word or Excel. Thanks!

**Pull request merged**
